//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IEA_ErpProject.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDoktorlar
    {
        public int Id { get; set; }
        public string Unvan { get; set; }
        public string Adi { get; set; }
        public Nullable<int> Hastane1id { get; set; }
        public Nullable<int> Hastane2id { get; set; }
        public Nullable<int> Hastane3id { get; set; }
        public string Muayenehane { get; set; }
        public string Tel1 { get; set; }
        public string Tel2 { get; set; }
        public string Gsm { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> DTarih { get; set; }
        public string VergiDairesi { get; set; }
        public string VergiNo { get; set; }
        public Nullable<int> SehirId { get; set; }
    
        public virtual tblHastaneler tblHastaneler { get; set; }
        public virtual tblHastaneler tblHastaneler1 { get; set; }
        public virtual tblHastaneler tblHastaneler2 { get; set; }
        public virtual Sehirler Sehirler { get; set; }
    }
}
